# Generated by Django 3.2.8 on 2021-10-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
    ]
