# Generated by Django 3.2.8 on 2021-10-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.CharField(default=123443553, max_length=10, verbose_name='Nascimento'),
            preserve_default=False,
        ),
    ]
